# config/database.yml

# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the `pg` gem:
#   gem install pg
#
# To use JRuby:
#   gem install jdbc-postgresql
#
# Configure using URL (recommended):
#
#   development:
#     url: postgresql://localhost/peak_box_app_development
#   test:
#     url: postgresql://localhost/peak_box_app_test
#
# Configure using host, port, username, and password:
#
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: admin # Usuario que creamos para desarrollo
  password: admin # Contraseña del usuario 'admin'

development:
  <<: *default
  database: peak_box_app_development

# Warning: The database defined as "test" will be erased and
# re-created to ensure clean test environment.
# This set of options can be changed with the --with-test-database
# flag on "rails db:migrate".
test:
  <<: *default
  database: peak_box_app_test

# Configuración de la base de datos para `cable` (SolidCable)
# Esta debe apuntar a la misma URL de la base de datos en producción.
cable:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

# As with config/credentials.yml, you should store your production database configuration here.
# In a production environment, your ENV['DATABASE_URL'] will be used to configure the database for Rails.
#
production:
  <<: *default
  # La siguiente línea es la clave para Heroku/Render.com. Usa la URL de la variable de entorno.
  url: <%= ENV['DATABASE_URL'] %>
  # Es importante que las siguientes líneas NO estén presentes o estén comentadas en producción si usas la URL
  # username: peakbox
  # password: <%= ENV['DATABASE_PASSWORD'] %>
